/**
 * Client-side file generation. No backend involved: we build the file in memory
 * and hand it to the browser. Swap for a server-rendered PDF endpoint later if
 * letterheaded documents are needed.
 */

export function downloadFile(filename: string, content: string, mime = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

function escapeCell(value: string | number): string {
  const s = String(value)
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

export function toCSV(rows: Record<string, string | number>[]): string {
  if (rows.length === 0) return ''
  const headers = Object.keys(rows[0])
  const lines = [
    headers.join(','),
    ...rows.map((row) => headers.map((h) => escapeCell(row[h] ?? '')).join(',')),
  ]
  return lines.join('\r\n')
}

export function downloadCSV(filename: string, rows: Record<string, string | number>[]) {
  downloadFile(filename, toCSV(rows), 'text/csv;charset=utf-8')
}

/** Turns a title into a safe filename stem: "Q3 Board Review" -> "q3-board-review" */
export function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export interface PdfSection {
  heading: string
  /** Paragraph text, or a list of bullet lines. */
  body?: string
  bullets?: string[]
}

/**
 * Renders a branded document and opens the browser's print dialog, from which
 * the user saves a real PDF. This is deliberately dependency-free: no PDF
 * library, just a print stylesheet. The SiteCommand name and rule brand it.
 */
export function printBrandedDocument(opts: {
  title: string
  subtitle?: string
  meta?: { label: string; value: string }[]
  sections: PdfSection[]
  footer?: string
}) {
  const metaRows = (opts.meta ?? [])
    .map((m) => `<tr><td class="mk">${escapeHtml(m.label)}</td><td class="mv">${escapeHtml(m.value)}</td></tr>`)
    .join('')

  const sections = opts.sections
    .map((s) => {
      const body = s.bullets
        ? `<ul>${s.bullets.map((b) => `<li>${escapeHtml(b)}</li>`).join('')}</ul>`
        : `<p>${escapeHtml(s.body ?? '')}</p>`
      return `<section><h2>${escapeHtml(s.heading)}</h2>${body}</section>`
    })
    .join('')

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(opts.title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: Arial, Helvetica, sans-serif; color: #181c25; margin: 0; padding: 40px 48px; line-height: 1.6; }
  .brand { font-size: 11px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; color: #f57e20; margin: 0; }
  h1 { font-size: 26px; margin: 4px 0 2px; }
  .sub { color: #5a616f; font-size: 14px; margin: 0 0 18px; }
  .rule { height: 3px; background: #f57e20; border-radius: 2px; margin: 0 0 22px; }
  table.meta { border-collapse: collapse; margin: 0 0 24px; font-size: 13px; }
  table.meta td { padding: 3px 0; }
  .mk { color: #8b93a3; padding-right: 24px !important; }
  .mv { font-weight: 600; }
  section { margin: 0 0 18px; }
  h2 { font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; color: #5a616f; border-bottom: 1px solid #e6e9ef; padding-bottom: 5px; margin: 0 0 8px; }
  p { margin: 0; font-size: 14px; white-space: pre-wrap; }
  ul { margin: 0; padding-left: 18px; font-size: 14px; }
  li { margin: 0 0 4px; }
  .foot { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e6e9ef; font-size: 11px; color: #8b93a3; }
  @media print { body { padding: 24px 28px; } @page { margin: 16mm; } }
</style></head><body>
  <p class="brand">SiteCommand</p>
  <h1>${escapeHtml(opts.title)}</h1>
  ${opts.subtitle ? `<p class="sub">${escapeHtml(opts.subtitle)}</p>` : ''}
  <div class="rule"></div>
  ${metaRows ? `<table class="meta">${metaRows}</table>` : ''}
  ${sections}
  <p class="foot">${escapeHtml(opts.footer ?? 'Generated by SiteCommand, the Operations Intelligence Platform.')}</p>
</body></html>`

  const w = window.open('', '_blank')
  if (!w) return // popup blocked; caller may fall back to text download
  w.document.write(html)
  w.document.close()
  // Give the new window a tick to lay out before printing.
  w.onload = () => { w.focus(); w.print() }
  setTimeout(() => { try { w.focus(); w.print() } catch { /* already printed */ } }, 400)
}
