import { useEffect, useState } from 'react'
import {
  CheckCircle2,
  Download,
  FileBadge,
  FileText,
  Image as ImageIcon,
  ShieldCheck,
  TrendingUp,
} from 'lucide-react'
import {
  KpiCard,
  PageHeader,
  Panel,
  Progress,
} from '../../components/ui'
import { ProductionTrend } from '../../components/charts'
import { useAuth } from '../../state/AuthContext'
import { useData } from '../../state/DataContext'
import { prettyDate } from '../../data/mockData'
import { fetchSiteProduction, formatDateLabel } from '../../lib/production'
import { fetchSitePhotos } from '../../lib/photos'
import type { SitePhoto } from '../../lib/photos'
import { fetchClientDocuments } from '../../lib/documents'
import type { ClientDocument } from '../../lib/documents'
import { printBrandedDocument } from '../../lib/download'

const photos = [
  { label: 'TSF Decant Station',  tone: 'from-amber-200 to-billnick-300' },
  { label: 'Slurry Pump Array',   tone: 'from-blue-200 to-blue-300' },
  { label: 'Haul Road & Berms',   tone: 'from-emerald-200 to-emerald-300' },
  { label: 'Process Plant',       tone: 'from-slate-200 to-slate-300' },
]

export default function ClientPortal() {
  const { user } = useAuth()
  const { siteViews, siteName, compliance } = useData()

  // Everything is keyed to the client's real Supabase site. No mock fallback.
  const siteId = user?.siteId ?? ''
  const siteView = siteViews.find((v) => v.id === siteId)
  const displayName = siteView?.name ?? (siteId ? siteName(siteId) : 'Your site')
  const siteCode = siteView?.code ?? '—'
  const siteLocation = siteView?.location ?? ''
  const commodity = 'Gold'
  const comp = compliance.bySite[siteId] ?? 100

  // Production trend, live from submitted daily reports (empty until any exist).
  const [trend, setTrend] = useState<{ date: string; actual: number; target: number }[]>([])
  const [realPhotos, setRealPhotos] = useState<SitePhoto[]>([])
  const [realDocs, setRealDocs] = useState<ClientDocument[]>([])

  // Try to load real Supabase production — siteId is a UUID for real users
  useEffect(() => {
    if (!user?.siteId) return
    fetchSiteProduction(user.siteId, 7).then((rows) => {
      setTrend(rows.map((r) => ({
        date: formatDateLabel(r.report_date),
        actual: r.production_tonnes_actual,
        target: r.production_tonnes_target,
      })))
    })
    fetchSitePhotos(user.siteId, 6).then(setRealPhotos)
    fetchClientDocuments(user.siteId).then(setRealDocs)
  }, [user?.siteId])

  const weekTotal = trend.reduce((s, t) => s + t.actual, 0)
  const weekTarget = trend.reduce((s, t) => s + t.target, 0)
  // Live progress toward target, from the real 7-day production figures.
  const targetProgress = weekTarget ? Math.min(100, Math.round((weekTotal / weekTarget) * 100)) : 0

  const issuedOn = new Date().toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  })

  // Generates a live production report PDF from the real figures on screen.
  function downloadProductionReport() {
    const variance = weekTarget ? Math.round(((weekTotal - weekTarget) / weekTarget) * 100) : 0
    printBrandedDocument({
      title: 'Production Report',
      subtitle: `Last 7 days · ${displayName}`,
      meta: [
        { label: 'Site', value: `${displayName} (${siteCode})` },
        { label: 'Location', value: siteLocation },
        { label: 'Commodity', value: commodity },
        { label: 'Issued', value: issuedOn },
        { label: 'Prepared for', value: `${user!.name}, ${user!.title.replace('Client, ', '')}` },
      ],
      sections: [
        {
          heading: 'Production summary, last 7 days',
          body: `Total actual: ${weekTotal.toLocaleString()} t\nTotal target: ${weekTarget.toLocaleString()} t\nVariance: ${variance >= 0 ? '+' : ''}${variance}%`,
        },
        {
          heading: 'Daily breakdown',
          bullets: trend.map((t) => `${t.date}: ${t.actual.toLocaleString()} t actual against ${t.target.toLocaleString()} t target`),
        },
        {
          heading: 'Compliance',
          body: `Compliance score: ${comp}%. All statutory certificates current at date of issue.`,
        },
      ],
      footer: 'Generated by BOIP. Figures are drawn from supervisor daily reports submitted at source.',
    })
  }

  return (
    <>
      <PageHeader
        title={`${displayName}, Client Portal`}
        subtitle={`${user!.title.replace('Client, ', '')} · ${siteLocation}`}
        action={
          <span className="pill bg-velron-500/10 text-velron-600">
            <ShieldCheck className="h-3.5 w-3.5" /> Client Access
          </span>
        }
      />

      <div className="mb-6 grid grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-4">
        <KpiCard label="Weekly Production"  value={weekTotal.toLocaleString()} unit="t"  icon={<TrendingUp className="h-5 w-5" />} accent="green"   delay={0} />
        <KpiCard label="Compliance Score"   value={comp}                        unit="%" icon={<ShieldCheck className="h-5 w-5" />} accent={comp >= 95 ? 'green' : 'billnick'} delay={50} />
        <KpiCard label="Reports Available"  value={realDocs.length + 1} icon={<FileText className="h-5 w-5" />} accent="blue" delay={100} />
        <KpiCard label="Commodity"          value={commodity} icon={<FileBadge className="h-5 w-5" />} accent="slate" sub={siteCode} delay={150} />
      </div>

      <div className="mb-6 grid gap-4 lg:grid-cols-3">
        <Panel title="Production Report, Last 7 Days" className="lg:col-span-2" icon={<TrendingUp className="h-4 w-4 text-billnick-500" />}>
          {trend.length ? (
            <ProductionTrend data={trend} />
          ) : (
            <p className="py-10 text-center text-sm text-ink-400">
              No production reported yet. Your site's daily reports will build this chart.
            </p>
          )}
        </Panel>
        <Panel title="Progress Summary">
          <div className="space-y-4">
            <div>
              <div className="mb-1 flex justify-between text-sm">
                <span className="text-ink-500">Production vs target</span>
                <span className="font-semibold text-ink-800">{targetProgress}%</span>
              </div>
              <Progress value={targetProgress} color="billnick" />
            </div>
            <div>
              <div className="mb-1 flex justify-between text-sm">
                <span className="text-ink-500">Compliance</span>
                <span className="font-semibold text-ink-800">{comp}%</span>
              </div>
              <Progress value={comp} color="green" />
            </div>
            <div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">
              <p className="flex items-center gap-1.5 font-semibold">
                <CheckCircle2 className="h-4 w-4" /> On schedule
              </p>
              <p className="mt-1 text-xs text-emerald-600">
                All compliance certificates current. Next progress report due end of month.
              </p>
            </div>
          </div>
        </Panel>
      </div>

      <div className="grid gap-4 lg:grid-cols-3">
        <Panel title="Documents & Deliverables" className="lg:col-span-2" icon={<FileText className="h-4 w-4 text-billnick-500" />}>
          {realDocs.length > 0 && (
            <div className="mb-2 space-y-2">
              {realDocs.map((doc) => (
                <div key={doc.id} className="flex items-center justify-between gap-3 rounded-xl border border-ink-100 p-3">
                  <div className="flex items-center gap-3 min-w-0">
                    <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-billnick-50 text-billnick-600">
                      <FileText className="h-4 w-4" />
                    </span>
                    <div className="min-w-0">
                      <p className="truncate text-sm font-semibold text-ink-800">{doc.title}</p>
                      <p className="text-xs text-ink-400">{doc.docType} · {prettyDate(doc.documentDate)}</p>
                    </div>
                  </div>
                  {doc.url ? (
                    <a href={doc.url} target="_blank" rel="noopener noreferrer" download={doc.fileName} className="btn-ghost shrink-0 px-3 py-1.5 text-xs">
                      <Download className="h-3.5 w-3.5" /> Download
                    </a>
                  ) : (
                    <span className="pill shrink-0 bg-ink-100 text-ink-500">Unavailable</span>
                  )}
                </div>
              ))}
            </div>
          )}
          <div className="space-y-2">
            {/* Always-available live production report, generated from real figures. */}
            <div className="flex items-center justify-between gap-3 rounded-xl border border-ink-100 p-3">
              <div className="flex items-center gap-3 min-w-0">
                <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-billnick-50 text-billnick-600">
                  <TrendingUp className="h-4 w-4" />
                </span>
                <div className="min-w-0">
                  <p className="truncate text-sm font-semibold text-ink-800">Production Report, last 7 days</p>
                  <p className="text-xs text-ink-400">Generated live · {issuedOn}</p>
                </div>
              </div>
              <button onClick={downloadProductionReport} className="btn-ghost shrink-0 px-3 py-1.5 text-xs">
                <Download className="h-3.5 w-3.5" /> Download PDF
              </button>
            </div>
            {realDocs.length === 0 && (
              <p className="rounded-xl bg-ink-50 px-3 py-2 text-xs text-ink-500">
                Reports and documents your project team publishes to you will appear here.
              </p>
            )}
          </div>
        </Panel>

        <Panel title="Site Photos" icon={<ImageIcon className="h-4 w-4 text-billnick-500" />}>
          {realPhotos.length > 0 ? (
            <>
              <div className="grid grid-cols-2 gap-2">
                {realPhotos.map((p) => (
                  <a
                    key={p.path}
                    href={p.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="group relative aspect-[4/3] overflow-hidden rounded-xl bg-ink-100"
                  >
                    <img
                      src={p.url}
                      alt={p.caption ?? `Site photo from ${prettyDate(p.date)}`}
                      loading="lazy"
                      className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
                    />
                    <div className="absolute inset-0 flex items-end bg-gradient-to-t from-black/50 to-transparent p-2 opacity-0 transition-opacity group-hover:opacity-100">
                      <span className="text-xs font-semibold text-white">{p.caption ?? 'View full size'}</span>
                    </div>
                    <span className="absolute left-2 top-2 rounded-md bg-white/85 px-1.5 py-0.5 text-[10px] font-medium text-ink-700">
                      {prettyDate(p.date)}
                    </span>
                  </a>
                ))}
              </div>
              <p className="mt-3 text-center text-xs text-ink-400">
                Captured on site with the daily reports · newest first
              </p>
            </>
          ) : (
            <>
              <div className="grid grid-cols-2 gap-2">
                {photos.map((p) => (
                  <div
                    key={p.label}
                    className={`group relative aspect-[4/3] overflow-hidden rounded-xl bg-gradient-to-br ${p.tone}`}
                  >
                    <div className="absolute inset-0 flex items-end bg-gradient-to-t from-black/40 to-transparent p-2 opacity-0 transition-opacity group-hover:opacity-100">
                      <span className="text-xs font-semibold text-white">{p.label}</span>
                    </div>
                  </div>
                ))}
              </div>
              <p className="mt-3 text-center text-xs text-ink-400">
                Placeholder imagery. Real site photos appear here once supervisors attach them to daily reports.
              </p>
            </>
          )}
        </Panel>
      </div>
    </>
  )
}
